### ISSUE TITLE
不懂就问，为什么我用openssl自己配置的证书没反应呀

### ISSUE THREAD

**Issue by miiiiiint** [HaneRo/MAA_TG_bot#1]
emmm，日志调成debug了也没反应，既不退出也不运行
我是新手。。。。。。。。
不太懂嗷

**Comment by HaneRo** [comment]
去掉第12行代码 `sys.stdout = open(os.devnull, "w") #使用pyinstaller  -w  时需重定向标准输出` 显示输出
安装依赖 pyTelegramBotAPI Flask `pip install pyTelegramBotAPI Flask`
你可以用浏览器打开  https://127.0.0.1:5000/getTask 一般会提示 "您的连接不是私密连接" “此服务器无法证明它是127.0.0.1；其安全证书来自XXXXX(某网址)。出现此问题的原因可能是配置有误或您的连接被拦截了。” 检查网址是否解析到本机；若提示“127.0.0.1 拒绝了我们的连接请求。”则Flask服务器未启动
使用浏览器 访问 https://你的网址:5000/getTask 会提示 “Method Not Allowed” 则可正常运行
初次使用先使用db.py 初始化数据库，对机器人发送/start 添加用户ID 之后再发送"/user XXXXXX " "/device YYYYYY"

**Comment by miiiiiint** [comment]
不太行，访问https://127.0.0.1:5000/getTask提示Method Not Allowed
访问自签证书的域名访问不上（不太懂这些emmmm）
然后干脆把证书删了，改成了ssl_context='adhoc'，然后日子改为debug，报错A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
但是就只有这一个进程，但是很惊讶的是，可以正常使用，所以应该是代码两个部分同时调用了token？（不太懂）
然后在maa上填入https://127.0.0.1:5000/getTask和https://127.0.0.1:5000/reportStatus，返回未能为ssl/tsl安全通道建立信任关系
所以是不是要必须去买域名才行，在网上看了一些办法，结果是看不懂。。。。。

**Comment by HaneRo** [comment]
你的自签证书的域名解析到本地了吗？或者修改hosts指向到本地也行；如果不用ssl 删除`, ssl_context=('server.crt', 'server.key')` 部分，但MAA不支持，你需要用nginx或其他程序反向代理
机器人同时只能有一个客户端连接，请检查是否多次运行脚本，或与其他脚本共用一个机器人

**Comment by miiiiiint** [comment]
![image](https://github.com/HaneRo/MAA_TG_bot/assets/99391147/18154e7a-3032-4ed1-97c5-75ef0d5cb5f4)
emmm，修改hosts指向本地了，如图所示，用自签证书尝试失败后，又换成了示例证书，还是不行来着，另外tgbot的话是我刚注册的，没有和其他脚本共用，只要将日志改成debug级别就能看见报错，我还重新了克隆一遍，防止是我对代码的改动照成了影响结果还是一样。但是不影响正常使用tgbot部分
我表示很难受的说。
![image](https://github.com/HaneRo/MAA_TG_bot/assets/99391147/5d0f31be-1eb8-454b-a2f9-6fb8b358d57e)

**Comment by HaneRo** [comment]
按理说如果能直接访问127.0.0.1，就说明Web服务器起来了，但是却不能用域名访问，你maa.lolicon.space没有走代理服务器吧？我只能想到这个问题，如果走了代理服务器会访问代理服务器的5000端口，自然也就拒绝访问了

**Comment by miiiiiint** [comment]
我靠，不愧是大佬，一针见血啊，为了访问github和tg用了v2ray，一看记录果然是这样，大佬太强了
![image](https://github.com/HaneRo/MAA_TG_bot/assets/99391147/fdee347a-35cc-44b8-973c-7b1d6faeb678)
